version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - allure_data:/var/jenkins_home/allure-results
      - allure_report:/var/jenkins_home/allure-report
    restart: unless-stopped

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cypress
    entrypoint: []   # override ENTRYPOINT to fix Cypress CMD parsing
    environment:
      - CYPRESS_allure=true
      - CYPRESS_allureResultsPath=/app/allure-results
      - ALLURE_REPORT=/app/allure-report
      - NO_COLOR=1
      - FORCE_COLOR=0
      - SPEC=cypress/e2e/1-getting-started/todo.cy.js
    volumes:
      - allure_data:/app/allure-results
      - allure_report:/app/allure-report
      - ./cypress:/app
    depends_on:
      - jenkins

volumes:
  jenkins_home:
  allure_data:
  allure_report:
